version: '3'

services:
  service:
    build: .
    ports:
      - "8096:8096"
    volumes:
      - ".:/usr/src/app"
    environment:
      - DB_HOST=db
      - stack=development
    depends_on:
      - db

  db:
    image: postgres:11
    restart: always
