version: '3'

services:
  db:
    image: postgres

  server:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=django_conf.settings
      - DB_HOST=db
      - stack=development
    depends_on:
      - db
    ports:
      - "8000:8000"
