version: '3'

services:
  db:
    image: postgres

  server:
    build: .
    command: python travelbear/manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=django_conf.settings
      - DB_HOST=db
      - stack=development
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - "8000:8000"
