# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2

jobs:
  # Run tests for the Travelbear service
  travelbear_test:
    working_directory: ~/srv
    docker:
    - image: circleci/python:3.7
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build images
        working_directory: ~/srv/Travelbear
        command: |
          docker-compose build
    - run:
        name: Check code style
        working_directory: ~/srv/Travelbear
        command: |
          docker-compose run --rm --no-deps server \
            sh -c "black --check . && isort -rc -q --check-only travelbear"
    - run:
        name: Run tests
        working_directory: ~/srv/Travelbear
        command: |
          docker-compose run --rm -e stack=test server \
            pytest

  gatekeeper_test:
    working_directory: ~/srv
    docker:
    - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lint code
          working_directory: ~/srv/Gatekeeper
          command: |
            [[ -z "$(gofmt -l .)" ]] \
              && (echo "Ok" && exit 0) || (echo "Code not formatted" && exit 1)
      - run:
          name: Run tests
          working_directory: ~/srv/Gatekeeper
          command: go test

workflows:
  version: 2
  test_services:
    jobs:
    - travelbear_test
    - gatekeeper_test
