# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2

jobs:
  # Run tests for the Travelbear service
  travelbear_test:
    working_directory: ~/srv
    docker:
    - image: circleci/python:3.7
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build images
        working_directory: ~/srv/travelbear
        command: |
          docker-compose build
    - run:
        name: Check code style
        working_directory: ~/srv/travelbear
        command: |
          docker-compose run --rm --no-deps server \
            sh -c "black --check . && isort -rc -q --check-only travelbear"
    - run:
        name: Run tests
        working_directory: ~/srv/travelbear
        command: |
          docker-compose run --rm -e stack=test server \
            pytest

workflows:
  version: 2
  travelbear:
    jobs:
    - travelbear_test
