# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2

jobs:
  build:
    working_directory: ~/tb
    docker:
    - image: circleci/python:3.7

    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build images
        command: |
          docker-compose build
    - run:
        name: Run tests
        command: |
          docker-compose run -e stack=test server \
            pytest --pyargs --doctest-modules --rootdir travelbear .
    - run:
        name: Run linter
        command: |
          docker-compose run -e stack=test server \
            black --fast --check --exclude db_layer/migrations travelbear
    - store_test_results:
        path: test-results
